// ~100 example spectrum pairs to inspire custom entries. Fully editable in the UI.
export const PRESETS = [
  ['Cold', 'Hot'],
  ['Underrated', 'Overrated'],
  ['Bad first date', 'Great first date'],
  ['Cheap', 'Expensive'],
  ['Boring superpower', 'Awesome superpower'],
  ['Bad smell', 'Good smell'],
  ['Small talk', 'Deep conversation'],
  ['Guilty pleasure', 'Actually just good'],
  ['Bad movie', 'Good movie'],
  ['Quiet', 'Loud'],
  ['Normal pet', 'Weird pet'],
  ['Not a superhero', 'Definitely a superhero'],
  ['Low effort costume', 'High effort costume'],
  ['Bad excuse', 'Good excuse'],
  ['Should stay a secret', 'Should be public knowledge'],
  ['Kid food', 'Adult food'],
  ['Overhyped', 'Underhyped'],
  ['Bad gift', 'Great gift'],
  ['Safe choice', 'Risky choice'],
  ['Villain move', 'Hero move'],
  ['Not a real job', 'Dream job'],
  ['Basic', 'Unique'],
  ['Petty', 'Justified'],
  ['Waste of money', 'Worth every penny'],
  ['Bad roommate habit', 'Ideal roommate habit'],
  ['Forgettable song', 'Instant classic'],
  ['Mild inconvenience', 'Major crisis'],
  ['Should be illegal', 'Should be mandatory'],
  ['Low stakes', 'High stakes'],
  ['Bad karaoke song', 'Great karaoke song'],
  ['Introvert energy', 'Extrovert energy'],
  ['Would not survive a horror movie', 'Final girl/guy energy'],
  ['Bad boss', 'Great boss'],
  ['Regular Tuesday', 'Main character energy'],
  ['Underpacked for a trip', 'Overpacked for a trip'],
  ['Toxic trait', 'Wholesome trait'],
  ['Bad text message habit', 'Good text message habit'],
  ['Skip it', 'Must-see'],
  ['Too spicy', 'Not spicy enough'],
  ['Bad nickname', 'Great nickname'],
  ['Chaotic', 'Organized'],
  ['Fake deep', 'Genuinely wise'],
  ['Would ruin a wedding', 'Would save a wedding'],
  ['Overkill', 'Not enough'],
  ['Bad first impression', 'Great first impression'],
  ['Low-key flex', 'Try-hard flex'],
  ['Should retire the trend', 'Timeless trend'],
  ['Cursed', 'Blessed'],
  ['Petty crime', 'Serious crime'],
  ['Not aging well', 'Aging like fine wine'],
  ['Bad camping trip', 'Great camping trip'],
  ['Awkward silence', 'Comfortable silence'],
  ['Overrated vacation spot', 'Underrated vacation spot'],
  ['Would fail immediately', 'Would ace it'],
  ['Rookie mistake', 'Expert move'],
  ['Bad party', 'Great party'],
  ['Forgettable', 'Iconic'],
  ['Too much effort', 'Not enough effort'],
  ['Should not be a competitive sport', 'Should be in the Olympics'],
  ['Bad roommate', 'Great roommate'],
  ['Overshare', 'Undershare'],
  ['Low budget movie', 'Blockbuster'],
  ['Bad advice', 'Good advice'],
  ['Petty argument', 'Serious argument'],
  ['Should be a red flag', 'Not actually a red flag'],
  ['Bland', 'Flavorful'],
  ['Bad luck', 'Good luck'],
  ['Would get you laughed out of the room', 'Would get a standing ovation'],
  ['Old-fashioned', 'Ahead of its time'],
  ['Too honest', 'Not honest enough'],
  ['Bad small talk topic', 'Great small talk topic'],
  ['Overdressed', 'Underdressed'],
  ['Bad workplace policy', 'Great workplace policy'],
  ['Not worth the hype', 'Lives up to the hype'],
  ['Petty revenge', 'Justified revenge'],
  ['Should not exist', 'Should exist everywhere'],
  ['Slow burn', 'Love at first sight'],
  ['Bad group chat energy', 'Good group chat energy'],
  ['Not photogenic', 'Extremely photogenic'],
  ['Would get voted off first', 'Would win the whole game'],
  ['Should be taught in school', 'Waste of class time'],
  ['Comfort food', 'Fancy dining'],
  ['Bad childhood memory', 'Core happy memory'],
  ['Overthinking it', 'Not thinking about it enough'],
  ['Would break the internet', 'Would go completely unnoticed'],
  ['Bad houseguest', 'Perfect houseguest'],
  ['Too niche', 'Universally relatable'],
  ['Bad dance move', 'Great dance move'],
  ['Should be banned from group trips', 'Ideal travel companion'],
  ['Petty grudge', 'Fully justified grudge'],
  ['Fashion disaster', 'Style icon'],
  ['Bad email etiquette', 'Good email etiquette'],
  ['Overqualified for the job', 'Underqualified for the job'],
  ['Would be the first to go', 'Would survive a zombie apocalypse'],
  ['Bad first line of a novel', 'Gripping first line'],
  ['Too much makeup', 'Not enough makeup'],
  ['Petty office politics', 'Genuine teamwork'],
  ['Should not be allowed on a resume', 'Great resume booster'],
  ['Bad Halloween candy', 'Best Halloween candy'],
  ['Small win', 'Life-changing win'],
]
